[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:redis]
command=redis-server --save "" --appendonly no --maxmemory 64mb --maxmemory-policy allkeys-lru
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:api]
command=gunicorn -b 0.0.0.0:8000 --workers 1 --threads 2 --timeout 300 django_react.wsgi
directory=/webapp
autostart=true
autorestart=true
startretries=5
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20
environment=DJANGO_SETTINGS_MODULE="django_react.settings_docker"

[program:celery]
command=celery -A api worker -l INFO -Q fast_queue,slow_queue --concurrency 1 --statedb=/webapp/celery/celery.state
directory=/webapp
autostart=true
autorestart=true
startretries=5
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=30
